//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoTemplate.Models
{
	/// <summary>Hero Content Controls</summary>
	[PublishedContentModel("heroContentControls")]
	public partial class HeroContentControls : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "heroContentControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeroContentControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroContentControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hero Button Text
		///</summary>
		[ImplementPropertyType("heroButtonText")]
		public string HeroButtonText
		{
			get { return this.GetPropertyValue<string>("heroButtonText"); }
		}

		///<summary>
		/// Hero Heading
		///</summary>
		[ImplementPropertyType("heroHeading")]
		public string HeroHeading
		{
			get { return this.GetPropertyValue<string>("heroHeading"); }
		}

		///<summary>
		/// Hero Image
		///</summary>
		[ImplementPropertyType("heroImage")]
		public IPublishedContent HeroImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("heroImage"); }
		}

		///<summary>
		/// Hero Link
		///</summary>
		[ImplementPropertyType("heroLink")]
		public Newtonsoft.Json.Linq.JToken HeroLink
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("heroLink"); }
		}

		///<summary>
		/// Hero Subheading
		///</summary>
		[ImplementPropertyType("heroSubheading")]
		public string HeroSubheading
		{
			get { return this.GetPropertyValue<string>("heroSubheading"); }
		}
	}
}
