//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoTemplate.Models
{
	/// <summary>Settings</summary>
	[PublishedContentModel("settings")]
	public partial class Settings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Settings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Settings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cache Buster
		///</summary>
		[ImplementPropertyType("cacheBuster")]
		public string CacheBuster
		{
			get { return this.GetPropertyValue<string>("cacheBuster"); }
		}

		///<summary>
		/// Coordinate
		///</summary>
		[ImplementPropertyType("coordinate")]
		public string Coordinate
		{
			get { return this.GetPropertyValue<string>("coordinate"); }
		}

		///<summary>
		/// Email Password
		///</summary>
		[ImplementPropertyType("emailPassword")]
		public string EmailPassword
		{
			get { return this.GetPropertyValue<string>("emailPassword"); }
		}

		///<summary>
		/// Email Sender
		///</summary>
		[ImplementPropertyType("emailSender")]
		public string EmailSender
		{
			get { return this.GetPropertyValue<string>("emailSender"); }
		}

		///<summary>
		/// Facebook App Id
		///</summary>
		[ImplementPropertyType("facebookAppId")]
		public string FacebookAppId
		{
			get { return this.GetPropertyValue<string>("facebookAppId"); }
		}

		///<summary>
		/// Favicon
		///</summary>
		[ImplementPropertyType("favicon")]
		public IPublishedContent Favicon
		{
			get { return this.GetPropertyValue<IPublishedContent>("favicon"); }
		}

		///<summary>
		/// Google Analytics Id
		///</summary>
		[ImplementPropertyType("googleAnalyticsId")]
		public string GoogleAnalyticsId
		{
			get { return this.GetPropertyValue<string>("googleAnalyticsId"); }
		}

		///<summary>
		/// Google API key
		///</summary>
		[ImplementPropertyType("googleAPIKey")]
		public string GoogleApikey
		{
			get { return this.GetPropertyValue<string>("googleAPIKey"); }
		}

		///<summary>
		/// Google Tag Manager Id
		///</summary>
		[ImplementPropertyType("googleTagManagerId")]
		public string GoogleTagManagerId
		{
			get { return this.GetPropertyValue<string>("googleTagManagerId"); }
		}

		///<summary>
		/// Mail Port
		///</summary>
		[ImplementPropertyType("mailPort")]
		public int MailPort
		{
			get { return this.GetPropertyValue<int>("mailPort"); }
		}

		///<summary>
		/// Mail Server
		///</summary>
		[ImplementPropertyType("mailServer")]
		public string MailServer
		{
			get { return this.GetPropertyValue<string>("mailServer"); }
		}

		///<summary>
		/// Map Default Zoom Level
		///</summary>
		[ImplementPropertyType("mapDefaultZoomLevel")]
		public int MapDefaultZoomLevel
		{
			get { return this.GetPropertyValue<int>("mapDefaultZoomLevel"); }
		}

		///<summary>
		/// Partial View Caching
		///</summary>
		[ImplementPropertyType("partialViewCaching")]
		public int PartialViewCaching
		{
			get { return this.GetPropertyValue<int>("partialViewCaching"); }
		}

		///<summary>
		/// Recaptcha Secret Key
		///</summary>
		[ImplementPropertyType("recaptchaSecretKey")]
		public string RecaptchaSecretKey
		{
			get { return this.GetPropertyValue<string>("recaptchaSecretKey"); }
		}

		///<summary>
		/// Recaptcha Site Key
		///</summary>
		[ImplementPropertyType("recaptchaSiteKey")]
		public string RecaptchaSiteKey
		{
			get { return this.GetPropertyValue<string>("recaptchaSiteKey"); }
		}

		///<summary>
		/// Site logo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public IPublishedContent SiteLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("siteLogo"); }
		}

		///<summary>
		/// Site Name
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		///<summary>
		/// Social network
		///</summary>
		[ImplementPropertyType("socialNetwork")]
		public Archetype.Models.ArchetypeModel SocialNetwork
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("socialNetwork"); }
		}

		///<summary>
		/// Use Ssl
		///</summary>
		[ImplementPropertyType("useSsl")]
		public bool UseSsl
		{
			get { return this.GetPropertyValue<bool>("useSsl"); }
		}
	}
}
