//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoTemplate.Models
{
	// Mixin content Type 1199 with alias "sliderControls"
	/// <summary>Slider Controls</summary>
	public partial interface ISliderControls : IPublishedContent
	{
		/// <summary>Sliders</summary>
		Archetype.Models.ArchetypeModel Sliders { get; }
	}

	/// <summary>Slider Controls</summary>
	[PublishedContentModel("sliderControls")]
	public partial class SliderControls : PublishedContentModel, ISliderControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sliderControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SliderControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SliderControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Sliders
		///</summary>
		[ImplementPropertyType("sliders")]
		public Archetype.Models.ArchetypeModel Sliders
		{
			get { return GetSliders(this); }
		}

		/// <summary>Static getter for Sliders</summary>
		public static Archetype.Models.ArchetypeModel GetSliders(ISliderControls that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("sliders"); }
	}
}
